// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3fo4qtzAQoQ9ziI0ZViu9BPfsREedakg',
    appId: '1:329261033564:web:73822256b45594f1ad1e99',
    messagingSenderId: '329261033564',
    projectId: 'tabungan-flutter-702f3',
    authDomain: 'tabungan-flutter-702f3.firebaseapp.com',
    databaseURL: 'https://tabungan-flutter-702f3-default-rtdb.firebaseio.com',
    storageBucket: 'tabungan-flutter-702f3.firebasestorage.app',
    measurementId: 'G-TV8WE8JM6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5X1Gx2krnBk1d2ZB5UBbnCJ7_zBzutHY',
    appId: '1:329261033564:android:2d9a62b128ed4aa5ad1e99',
    messagingSenderId: '329261033564',
    projectId: 'tabungan-flutter-702f3',
    databaseURL: 'https://tabungan-flutter-702f3-default-rtdb.firebaseio.com',
    storageBucket: 'tabungan-flutter-702f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVh7f5Fvz1WILckxb6BsVlEm8XK8KZ5E',
    appId: '1:329261033564:ios:00c37abb5b727d24ad1e99',
    messagingSenderId: '329261033564',
    projectId: 'tabungan-flutter-702f3',
    databaseURL: 'https://tabungan-flutter-702f3-default-rtdb.firebaseio.com',
    storageBucket: 'tabungan-flutter-702f3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVh7f5Fvz1WILckxb6BsVlEm8XK8KZ5E',
    appId: '1:329261033564:ios:00c37abb5b727d24ad1e99',
    messagingSenderId: '329261033564',
    projectId: 'tabungan-flutter-702f3',
    databaseURL: 'https://tabungan-flutter-702f3-default-rtdb.firebaseio.com',
    storageBucket: 'tabungan-flutter-702f3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3fo4qtzAQoQ9ziI0ZViu9BPfsREedakg',
    appId: '1:329261033564:web:0babda44b49cbfe9ad1e99',
    messagingSenderId: '329261033564',
    projectId: 'tabungan-flutter-702f3',
    authDomain: 'tabungan-flutter-702f3.firebaseapp.com',
    databaseURL: 'https://tabungan-flutter-702f3-default-rtdb.firebaseio.com',
    storageBucket: 'tabungan-flutter-702f3.firebasestorage.app',
    measurementId: 'G-MSYH4N4VP0',
  );
}
